---
title: "2_netwerk_ankervakken"
output: html_document
---

```{r preparation}
# Packages
library(dplyr)
library(ggplot2)
library(reshape2)
library(lubridate)
library(BiocGenerics)
library(network)
library(gmodels)
library(graph)
library(GGally)
library(sna)

set.seed(1)

# Data ophalen
load('../Data/1_reading_cleaning/afstanden_9d_combis.Rda')

# Dataset transposen; combi's onder elkaar zetten
afstanden_melt <- melt(afstanden_9d_combis, id.vars = c("X","A"))
afstanden_melt <-
  afstanden_melt %>%
  arrange(variable, A) %>%
  mutate(value = as.numeric(value))

```

```{r sample}
# Sample van een x aantal combis. Overschrijft de volledige set. Geen sample? Dan deze chunk niet runnen.
n_combi <- 20
row_nrs <- round(runif(n_combi, 1, length(unique(afstanden_melt$variable))), 0)
afstanden_melt <-
  afstanden_melt %>%
  filter(variable %in% unique(afstanden_melt$variable)[row_nrs])

```

### Tijd x afstand
Geeft onderlinge afstand combinaties in de tijd weer

```{r plot_time_dist}
ggplot(afstanden_melt, aes(x = A, y = value, color = variable)) +
  geom_line(size = 1, show.legend = FALSE) +
  xlab("Datum + tijd") +
  ylab("Afstand")

```

```{r prep_network}
# Minimale afstand per combinatie wegschrijven in een data frame
min_afstand <- data.frame()
for (i in 1:length(unique(afstanden_melt$variable))) {
  
  selectie_i <- afstanden_melt %>% filter(variable == unique(afstanden_melt$variable)[i])
  
  min_afstand_i <- selectie_i[which.min(selectie_i$value),]
  
  min_afstand <- bind_rows(min_afstand, min_afstand_i)
  
}

# Minimale afstand met bandbreedte (percentage) in combinatie met tijdsduur wegschrijven in data frame
min_afstand_tijd <- data.frame()
bandbreedte <- .1

for (i in 1:length(unique(afstanden_melt$variable))) {
  
  selectie_i <- afstanden_melt %>% filter(variable == unique(afstanden_melt$variable)[i])
  
  min_afstand_tijd_i <-
    selectie_i %>%
    filter(value <= (1 + bandbreedte) * selectie_i[which.min(selectie_i$value),4])

  min_afstand_tijd <- bind_rows(min_afstand_tijd, min_afstand_tijd_i)
  
}

min_afstand_tijd <-
  min_afstand_tijd %>%
  group_by(combi = variable) %>%
  summarise(t_start = min(A), t_eind = max(A), d_min = min(value), d_max = max(value)) %>%
  mutate(delta_d = d_max - d_min) %>%
  mutate(delta_t = difftime(t_eind, t_start))

# Combi splitsen in twee kolommen
min_afstand_tijd$schip_1 <-
  sapply(min_afstand_tijd$combi,
         function(y) substr(y, 1, regexpr("...", y, fixed = TRUE)[1] - 1))
min_afstand_tijd$schip_2 <-
  sapply(min_afstand_tijd$combi,
         function(y) substr(y, regexpr("...", y, fixed = TRUE)[1] + 3, nchar(as.character(y))))

# NAs niet meenemen.
min_afstand_tijd <-
  min_afstand_tijd %>%
  filter(schip_1 != "nan" & schip_2 != "nan")

# Edge list
data_netwerk <-
  min_afstand_tijd %>%
  select(schip_1, schip_2, d_min) %>%
  arrange(d_min)

# Combinaties komen allemaal twee keer voor, waarbij de volgorde van schepen is omgedraaid. Hierop ontdubbelen,
data_netwerk <-
  data_netwerk %>%
  filter((schip_1 != lead(schip_2)) | (schip_2 != lead(schip_1)))

# Van edge list naar adjacency matrix
adj_matrix <- ftM2adjM(as.matrix(data_netwerk[,1:2]), W=data_netwerk$d_min)

# Netwerkje maken
netwerk_input <- network(adj_matrix, directed=FALSE)

# Edge size bepalen
edgesize <- mean(data_netwerk$d_min) / data_netwerk$d_min

```

### Netwerk onderlinge afstand schepen
Let op: dikte lijn en NIET lengte representeert afstand (verwarrend...)

```{r netwerk}

# Netwerk visualiseren
ggnet2(
  netwerk_input,
  node.color = "green",
  edge.size = edgesize,
  label = TRUE,
  label.size = 3
)

```


